### ISSUE TITLE
triggers asserts in irssi on SSL handshake failure

### ISSUE THREAD

**Issue by jelmer** [phhusson/quassel-irssi#1]
Connecting to my quassel instance fails because of SSL issues. I haven't figured out why yet. 

However, this also triggers various asserts in irssi itself. 

02:08 -!- Irssi: Loaded module quassel/core
02:08 -!- Irssi: Connecting to myhost.mydomain.nl [2a01::something] port 4242
02:08 -!- Irssi: warning SSL handshake failed: server closed connection unexpectedly
02:08 -!- Irssi: Connection lost to myhost.mydomain.nl
02:08 -!- Irssi: critical server_connect_copy_skeleton: assertion 'dest != NULL' failed
02:08 -!- Irssi: critical sig_reconnect: assertion 'conn != NULL' failed

**Comment by alexfornuto** [comment]
I am also having this issue. Can you clarify on the irssi headers file?
