### ISSUE TITLE
warning when connecting to quasselcore

### ISSUE THREAD

**Issue by jelmer** [phhusson/quassel-irssi#12]
Presumably this could be fixed by a g_io_channel_set_buffered() call somewhere..:

14:47 -!- Irssi: warning Need to set the channel buffered before setting the encoding.
14:47 -!- Irssi: 
14:47 -!- Irssi: warning Assuming this is what you meant and acting accordingly.
14:47 -!- Irssi:

**Comment by dabbill** [comment]
I am noticing this as well when connecting to quasselcore. Is there a way to fix this, or am I just missing a setting somewhere.

**Comment by jelmer** [comment]
On Wed, Jun 08, 2016 at 05:16:56PM -0700, Ryan Gillette wrote:
> I am noticing this as well when connecting to quasselcore. Is there a way to fix this, or am I just missing a setting somewhere. 
It's not a setting. This is just a bug in quassel-irssi. :)
