### ISSUE TITLE
implementation of an "abi check" in 0.8.18

### ISSUE THREAD

**Issue by ailin-nemui** [phhusson/quassel-irssi#13]
Hi, we added some compile-time constant to stop irssi from crashing with modules compiled into different irssi versions. To use it, please include

```
#ifdef IRSSI_ABI_VERSION
void //MODULENAME//_abicheck(int *version)
{
    *version = IRSSI_ABI_VERSION;
}
#endif
```
next to your `_init` and `_deinit` functions. sorry for the inconvenience!

**Comment by phhusson** [comment]
Oh, that's nice
Thanks for the info
