### ISSUE TITLE
quassel_core_abicheck needs to be declared in a header

### ISSUE THREAD

**Issue by TC01** [phhusson/quassel-irssi#14]
I was curious if the ABI detection change would stop the crash I was experiencing in #3, so I tried building (on a VM) a copy of latest irssi and also latest quassel-irssi.

It seems that something like the following needs to be added to the end of [quassel-irssi.h](https://github.com/phhusson/quassel-irssi/blob/master/core/quassel-irssi.h) for the code in 575d9b2194a51399ee2316134cdf66b1ce86fd21 to build?

```c
#ifdef IRSSI_ABI_VERSION
void quassel_core_abicheck(int *version);
#endif
```

Adding those lines to that file allowed me to build quassel-irssi again.

**Comment by TC01** [comment]
...apparently I was wrong about this, because I just tried to build on a different system and it worked perfectly. 

Well, sorry for a spurious bug report then. :(

**Comment by phhusson** [comment]
Good thing I procrastinated this then :)
Thanks for your tests

**Comment by TC01** [comment]
Mind you, it just occurred to me that it's possible that IRSSI_ABI_VERSION wasn't defined on whatever system I was building on, and that's why I got different behavior? So maybe this actually is a problem after all.

Happy to test! I really like having a headless quassel client when necessary. :)

**Comment by hurricanehrndz** [comment]
Yes this is an error.
