### ISSUE TITLE
License incompatibility for GPLv2 / OpenSSL

### ISSUE THREAD

**Issue by jelmer** [phhusson/quassel-irssi#20]
Quassel-irssi is licensed under the GPL but links against OpenSSL. See also https://lintian.debian.org/tags/possible-gpl-code-linked-with-openssl.html

irssi does the same, but has an explicit exception for this in COPYING:

   Specific permission is granted for the GPLed code in this
   distribition to be linked to OpenSSL without invoking GPL clause
   2(b).

Would it be possible to have a similar exception for both quasselc and quassel-irssi?

Thanks,

Jelmer

**Comment by phhusson** [comment]
AFAIK, QuasselC doesn't call anything OpenSSL-related (though QuasselBots should)
Now, when it comes to quassel-irssi, I don't really rely on OpenSSL.

The only reason I do, is because from an irssi plugin, I don't have access to irssi's SSL API, thus I have to copy/paste irsssi's network-openssl.c...

I really don't like the look of the exception, but for quassel-irssi I don't really mind

**Comment by jelmer** [comment]
The problem for quasselc is that it is GPLv3 code that is linked into a binary with OpenSSL, which means it'll also need the exception (or be under a license that's compatible with the OpenSSL license).

**Comment by phhusson** [comment]
You mean if a software A wants to rely on OpenSSL and library B
Then library B needs to have the OpenSSL exception, even if library B doesn't care at all about OpenSSL?

Like if libpcre is in GPLv3, it needs an OpenSSL exception to be used in any software using OpenSSL, even though it has nothing to do with OpenSSL?

Or what you said only applies when static linking perhaps?

**Comment by jelmer** [comment]
If library B is GPL (rather than say, LGPL, like glib) then yes. Many libraries are e.g. LGPL, and some software uses GNUTLS rather than OpenSSL to avoid this problem.

Static linking doesn't make a difference  - see https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic

**Comment by phhusson** [comment]
Right, that's more the issue.
You're the only external contributor to quasselc, do you agree to switch it to LGPLv3?

**Comment by jelmer** [comment]
Yes, that would be fine with me.

**Comment by jelmer** [comment]
Thanks for fixing this!

**Comment by ailin-nemui** [comment]
hi, instead of copying irssi files it may be better to open a request on irssi to check for a better solution

**Comment by jelmer** [comment]
On Tue, Jan 10, 2017 at 03:11:03AM -0800, ailin-nemui wrote:
> hi, instead of copying irssi files it may be better to open a request on irssi to check for a better solution
That would indeed be useful, though it's orthogonal to this issue of licensing.
You'd still need the exception since irssi-quassel links against irssi.
