### ISSUE TITLE
Leaks memory

### ISSUE THREAD

**Issue by jelmer** [phhusson/quassel-irssi#6]
After running one day, irssi is using about 3Gb of memory.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND          
31955 jelmer    20   0 6354056 3.037g    720 R  35.6 39.7  21:04.02 irssi

**Comment by phhusson** [comment]
No more report, and I've tested again with valgrind, and nothing raises, so I'd guess it's ok
